# Creando el grafo

Hemos leído ya el repertorio de la pagina https://www.allmusic.com/ para la lista de artistas que disponemos. Estos datos contienen 4 campos:

- Identificador del artista
- Nombre del artista
- Identificador del artista con el que comparte una cancion
- Cancion que comparten

El objetivo es obtener un documento en el cual tengamos unicamente los nombres de los artistas que son los extremos de la arista y el peso de la arista, del tipo.

|Artist|Collaborator|Number collaborations|
|--|--|--|
|Metallica|ACDC|6|

In [183]:
import pandas as pd
import unidecode

In [185]:
# Primero leo el repertorio
repertorio = pd.read_csv('./graph_project_crawl/Repertorio-Final.csv',
                         sep=',', 
                         encoding='utf-8',
                         index_col = None)

# Todas las canciones a minúscula
repertorio['song'] = repertorio['song'].str.lower()

""" Elimina los acentos en las canciones"""
repertorio['song'] = repertorio['song'].str.normalize('NFD').str.encode('ascii', errors='ignore').str.decode('utf-8')
repertorio.head(5)

,artist_id,artist_name,feat_artist_id,feat_artist_name,song
0,mn0000690254,ZZ Top,mn0000503563,The Moving Sidewalks,you make me shake
1,mn0000690254,ZZ Top,mn0000503563,The Moving Sidewalks,you were so close to me
2,mn0000246960,Wham!,mn0000545074,George Michael,young guns
3,mn0000246960,Wham!,mn0000545074,George Michael,young guns
4,mn0000246960,Wham!,mn0000545074,George Michael,young guns (go for it!)

In [186]:
# Ordeno el repertorio por el nombre del artísta
repertorio = repertorio.sort_values(by='artist_name')
repertorio.head()

,artist_id,artist_name,feat_artist_id,feat_artist_name,song
5671,mn0000516929,*NSYNC,mn0000567809,Modern Talking,you got it
5770,mn0000516929,*NSYNC,mn0000101895,Joe,i'll never stop(vcd)
5771,mn0000516929,*NSYNC,mn0000101895,Joe,if i'm not the one
5772,mn0000516929,*NSYNC,mn0000101895,Joe,if i'm not the one
5773,mn0000516929,*NSYNC,mn0000101895,Joe,if only in heaven's eyes

In [187]:
# Hay cancionoes duplicadas (featurings duplicados), los elimino
repertorio = repertorio.drop_duplicates(subset=repertorio.columns).reset_index(drop=True)

In [188]:
repertorio['Number collaborations'] = 1
repertorio.head()

,artist_id,artist_name,feat_artist_id,feat_artist_name,song,Number collaborations
0,mn0000516929,*NSYNC,mn0000567809,Modern Talking,you got it,1
1,mn0000516929,*NSYNC,mn0000101895,Joe,i'll never stop(vcd),1
2,mn0000516929,*NSYNC,mn0000101895,Joe,if i'm not the one,1
3,mn0000516929,*NSYNC,mn0000101895,Joe,if only in heaven's eyes,1
4,mn0000516929,*NSYNC,mn0000101895,Joe,in conversation,1

In [189]:
f = {'Number collaborations': 'sum', 'artist_name': 'first', 'feat_artist_name': 'first'}
test = repertorio.groupby(['artist_id', 'feat_artist_id'],
                          as_index=False).agg(f)


test.head()

,artist_id,feat_artist_id,Number collaborations,artist_name,feat_artist_name
0,mn0000000534,mn0000344634,10,All Saints,Melanie Blatt
1,mn0000000534,mn0000642542,6,All Saints,Burt Bacharach
2,mn0000000534,mn0000815862,8,All Saints,All-Saints Ensemble
3,mn0000000534,mn0001233067,50,All Saints,Danny Thompson
4,mn0000002578,mn0000236246,19,Tanita Tikaram,Mark Isham

In [191]:
output = pd.DataFrame()
for _, row in test.iterrows():
    inverted = test[(test['artist_name'] == row['feat_artist_name']) & (test['feat_artist_name'] == row['artist_name'])]

         artist_id feat_artist_id  Number collaborations artist_name  \
1745  mn0000239827   mn0000005307                      7  John Mayer

     feat_artist_name
1745      Alicia Keys
        artist_id feat_artist_id  Number collaborations artist_name  \
125  mn0000021009   mn0000005953                      6       Slash

    feat_artist_name
125     Alice Cooper
         artist_id feat_artist_id  Number collaborations  artist_name  \
1808  mn0000255210   mn0000006334                     85  Diana Krall

     feat_artist_name
1808     Tony Bennett
         artist_id feat_artist_id  Number collaborations    artist_name  \
2243  mn0000317093   mn0000006334                     41  Nat King Cole

     feat_artist_name
2243     Tony Bennett
         artist_id feat_artist_id  Number collaborations artist_name  \
4186  mn0000796734   mn0000006334                     30  Elton John

     feat_artist_name
4186     Tony Bennett
         artist_id feat_artist_id  Number collaborations    artist_name  \
4568  mn0000869068   mn0000006855                     27  Mercedes Sosa

     feat_artist_name
4568    Pablo Milanés
         artist_id feat_artist_id  Number collaborations artist_name  \
2109  mn0000295756   mn0000010904                     40     Santana

        feat_artist_name
2109  Patricia Manterola
       artist_id feat_artist_id  Number collaborations   artist_name  \
35  mn0000005953   mn0000021009                     98  Alice Cooper

   feat_artist_name
35            Slash
         artist_id feat_artist_id  Number collaborations    artist_name  \
2514  mn0000363307   mn0000021009                      5  Marta Sánchez

     feat_artist_name
2514            Slash
        artist_id feat_artist_id  Number collaborations     artist_name  \
743  mn0000102985   mn0000025597                     23  Julio Iglesias

    feat_artist_name
743  Andrés Calamaro
         artist_id feat_artist_id  Number collaborations    artist_name  \
1206  mn0000172360   mn0000026061                    172  Víctor Manuel

     feat_artist_name
1206        Ana Belén
         artist_id feat_artist_id  Number collaborations artist_name  \
1226  mn0000175874   mn0000026061                     10   Fito Páez

     feat_artist_name
1226        Ana Belén
         artist_id feat_artist_id  Number collaborations  artist_name  \
2868  mn0000492846   mn0000026061                    169  Miguel Ríos

     feat_artist_name
2868        Ana Belén
         artist_id feat_artist_id  Number collaborations artist_name  \
4259  mn0000805858   mn0000026061                      2      Estopa

     feat_artist_name
4259        Ana Belén
        artist_id feat_artist_id  Number collaborations artist_name  \
777  mn0000108323   mn0000027136                      8        Coti

    feat_artist_name
777    Paulina Rubio
        artist_id feat_artist_id  Number collaborations artist_name  \
612  mn0000085915   mn0000029884                     38  Billy Joel

    feat_artist_name
612   Paul McCartney
         artist_id feat_artist_id  Number collaborations  artist_name  \
1671  mn0000232564   mn0000029884                     61  John Lennon

     feat_artist_name
1671   Paul McCartney
         artist_id feat_artist_id  Number collaborations  artist_name  \
3817  mn0000754032   mn0000029884                     83  The Beatles

     feat_artist_name
3817   Paul McCartney
        artist_id feat_artist_id  Number collaborations artist_name  \
758  mn0000107090   mn0000031442                      5        Cher

    feat_artist_name
758        Anastacia
         artist_id feat_artist_id  Number collaborations artist_name  \
1238  mn0000176358   mn0000031442                     13  Jamiroquai

     feat_artist_name
1238        Anastacia
         artist_id feat_artist_id  Number collaborations      artist_name  \
3231  mn0000601079   mn0000031442                     24  Eros Ramazzotti

     feat_artist_name
3231        Anastacia
         artist_id feat_artist_id  Number collaborations    artist_name  \
4275  mn0000810166   mn0000031442                     12  Vonda Shepard

     feat_artist_name
4275        Anastacia
        artist_id feat_artist_id  Number collaborations artist_name  \
217  mn0000031442   mn0001521636                     13   Anastacia

    feat_artist_name
217        Anastacia
         artist_id feat_artist_id  Number collaborations artist_name  \
2432  mn0000354733   mn0000031685                     19   Los Lobos

     feat_artist_name
2432       Paul Simon
         artist_id feat_artist_id  Number collaborations   artist_name  \
3182  mn0000585249   mn0000031685                     31  Annie Lennox

     feat_artist_name
3182       Paul Simon
         artist_id feat_artist_id  Number collaborations artist_name  \
1710  mn0000237205   mn0000032438                     30     Madonna

     feat_artist_name
1710      Andrea Corr
         artist_id feat_artist_id  Number collaborations    artist_name  \
2919  mn0000504815   mn0000038936                     36  Art Garfunkel

       feat_artist_name
2919  Simon & Garfunkel
        artist_id feat_artist_id  Number collaborations artist_name  \
613  mn0000085915   mn0000046861                     23  Billy Joel

    feat_artist_name
613      Ray Charles
        artist_id feat_artist_id  Number collaborations  artist_name  \
950  mn0000137494   mn0000046861                     17  Fats Domino

    feat_artist_name
950      Ray Charles
         artist_id feat_artist_id  Number collaborations  artist_name  \
2714  mn0000423829   mn0000046861                     49  Miles Davis

     feat_artist_name
2714      Ray Charles
         artist_id feat_artist_id  Number collaborations      artist_name  \
4726  mn0000927555   mn0000046861                     42  Aretha Franklin

     feat_artist_name
4726      Ray Charles
         artist_id feat_artist_id  Number collaborations       artist_name  \
2216  mn0000314505   mn0000052062                     14  Vanessa Williams

     feat_artist_name
2216         Chayanne
         artist_id feat_artist_id  Number collaborations     artist_name  \
2257  mn0000317865   mn0000052062                     12  Jennifer Lopez

     feat_artist_name
2257         Chayanne
         artist_id feat_artist_id  Number collaborations artist_name  \
2583  mn0000379125   mn0000066915                     39  Neil Young

     feat_artist_name
2583        Bob Dylan
         artist_id feat_artist_id  Number collaborations  artist_name  \
4299  mn0000816890   mn0000066915                     42  Johnny Cash

     feat_artist_name
4299        Bob Dylan
         artist_id feat_artist_id  Number collaborations     artist_name  \
3790  mn0000751613   mn0000068934                    115  Andrea Bocelli

     feat_artist_name
3790          Kenny G
         artist_id feat_artist_id  Number collaborations   artist_name  \
1219  mn0000175286   mn0000069986                     65  Dolly Parton

     feat_artist_name
1219     Kenny Rogers
        artist_id feat_artist_id  Number collaborations    artist_name  \
592  mn0000083013   mn0000070929                    105  The Jackson 5

    feat_artist_name
592     The Jacksons
         artist_id feat_artist_id  Number collaborations      artist_name  \
2773  mn0000467203   mn0000070929                     58  Michael Jackson

     feat_artist_name
2773     The Jacksons
         artist_id feat_artist_id  Number collaborations   artist_name  \
1457  mn0000204386   mn0000074195                     27  James Taylor

     feat_artist_name
1457     Natalie Cole
        artist_id feat_artist_id  Number collaborations  artist_name  \
542  mn0000080780   mn0000075591                     30  Sheryl Crow

    feat_artist_name
542        The Corrs
         artist_id feat_artist_id  Number collaborations     artist_name  \
3381  mn0000619388   mn0000075591                     15  Alejandro Sanz

     feat_artist_name
3381        The Corrs
        artist_id feat_artist_id  Number collaborations artist_name  \
510  mn0000075591   mn0000080780                     13   The Corrs

    feat_artist_name
510      Sheryl Crow
         artist_id feat_artist_id  Number collaborations   artist_name  \
1932  mn0000268161   mn0000082482                     10  Diego Torres

     feat_artist_name
1932           Ketama
         artist_id feat_artist_id  Number collaborations   artist_name  \
2878  mn0000494368   mn0000082482                     21  Antonio Vega

     feat_artist_name
2878           Ketama
         artist_id feat_artist_id  Number collaborations     artist_name  \
2883  mn0000494672   mn0000082482                      5  Antonio Flores

     feat_artist_name
2883           Ketama
         artist_id feat_artist_id  Number collaborations     artist_name  \
3479  mn0000639397   mn0000082482                      2  Caetano Veloso

     feat_artist_name
3479           Ketama

        artist_id feat_artist_id  Number collaborations   artist_name  \
458  mn0000070929   mn0000083013                     69  The Jacksons

    feat_artist_name
458    The Jackson 5
         artist_id feat_artist_id  Number collaborations      artist_name  \
2774  mn0000467203   mn0000083013                    332  Michael Jackson

     feat_artist_name
2774    The Jackson 5
        artist_id feat_artist_id  Number collaborations     artist_name  \
191  mn0000029884   mn0000085915                     56  Paul McCartney

    feat_artist_name
191       Billy Joel
        artist_id feat_artist_id  Number collaborations  artist_name  \
315  mn0000046861   mn0000085915                     56  Ray Charles

    feat_artist_name
315       Billy Joel
         artist_id feat_artist_id  Number collaborations artist_name  \
3275  mn0000606283   mn0000088035                      7  Al Jarreau

     feat_artist_name
3275      Kelly Price
         artist_id feat_artist_id  Number collaborations      artist_name  \
1823  mn0000255733   mn0000089021                     58  Johnny Hallyday

     feat_artist_name
1823       Jimmy Page
         artist_id feat_artist_id  Number collaborations   artist_name  \
4335  mn0000830538   mn0000089021                    148  Robert Plant

     feat_artist_name
4335       Jimmy Page
        artist_id feat_artist_id  Number collaborations  artist_name  \
888  mn0000128099   mn0000093632                     48  James Brown

    feat_artist_name
888    Robert Palmer
        artist_id feat_artist_id  Number collaborations    artist_name  \
785  mn0000109414   mn0000095243                      4  Courtney Love

    feat_artist_name
785      Kurt Cobain
         artist_id feat_artist_id  Number collaborations artist_name  \
3247  mn0000602378   mn0000101072                     19   Timbaland

        feat_artist_name
3247  The Pussycat Dolls
        artist_id feat_artist_id  Number collaborations      artist_name  \
139  mn0000025597   mn0000102985                      7  Andrés Calamaro

    feat_artist_name
139   Julio Iglesias
         artist_id feat_artist_id  Number collaborations    artist_name  \
2921  mn0000504815   mn0000102985                     10  Art Garfunkel

     feat_artist_name
2921   Julio Iglesias
         artist_id feat_artist_id  Number collaborations      artist_name  \
3233  mn0000601079   mn0000102985                     22  Eros Ramazzotti

     feat_artist_name
3233   Julio Iglesias
        artist_id feat_artist_id  Number collaborations artist_name  \
207  mn0000031442   mn0000107090                      3   Anastacia

    feat_artist_name
207             Cher
         artist_id feat_artist_id  Number collaborations      artist_name  \
3234  mn0000601079   mn0000107090                     20  Eros Ramazzotti

     feat_artist_name
3234             Cher
        artist_id feat_artist_id  Number collaborations  artist_name  \
914  mn0000130050   mn0000107949                      6  Pasión Vega

    feat_artist_name
914   Ismael Serrano
        artist_id feat_artist_id  Number collaborations         artist_name  \
981  mn0000138672   mn0000107949                     51  Joan Manuel Serrat

    feat_artist_name
981   Ismael Serrano
         artist_id feat_artist_id  Number collaborations   artist_name  \
1794  mn0000252978   mn0000107949                     13  Pedro Guerra

     feat_artist_name
1794   Ismael Serrano
        artist_id feat_artist_id  Number collaborations    artist_name  \
170  mn0000027136   mn0000108323                     28  Paulina Rubio

    feat_artist_name
170             Coti
         artist_id feat_artist_id  Number collaborations      artist_name  \
4382  mn0000836376   mn0000108323                     12  Julieta Venegas

     feat_artist_name
4382             Coti
         artist_id feat_artist_id  Number collaborations artist_name  \
4443  mn0000846787   mn0000108323                      1      Pereza

     feat_artist_name
4443             Coti
        artist_id feat_artist_id  Number collaborations  artist_name  \
714  mn0000095243   mn0000109414                      5  Kurt Cobain

    feat_artist_name
714    Courtney Love
         artist_id feat_artist_id  Number collaborations artist_name  \
5050  mn0002053263   mn0000115478                      7    Pignoise

     feat_artist_name
5050        Cómplices
         artist_id feat_artist_id  Number collaborations artist_name  \
3958  mn0000771470   mn0000116178                     23  Boy George

     feat_artist_name
3958     Culture Club
         artist_id feat_artist_id  Number collaborations      artist_name  \
2303  mn0000332141   mn0000120521                     99  Jerry Lee Lewis

     feat_artist_name
2303      Chuck Berry
         artist_id feat_artist_id  Number collaborations artist_name  \
3851  mn0000757085   mn0000122754                      9     Bangles

     feat_artist_name
3851     Cyndi Lauper
         artist_id feat_artist_id  Number collaborations   artist_name  \
1368  mn0000187478   mn0000124492                    109  Eric Clapton

     feat_artist_name
1368             Beck
         artist_id feat_artist_id  Number collaborations   artist_name  \
4542  mn0000862671   mn0000127967                      6  Lucie Silvas

     feat_artist_name
4542   Antonio Orozco
         artist_id feat_artist_id  Number collaborations artist_name  \
4961  mn0001411209   mn0000127967                      3     Natalia

     feat_artist_name
4961   Antonio Orozco
        artist_id feat_artist_id  Number collaborations    artist_name  \
684  mn0000093632   mn0000128099                     29  Robert Palmer

    feat_artist_name
684      James Brown
         artist_id feat_artist_id  Number collaborations        artist_name  \
2200  mn0000312890   mn0000128440                     10  Justin Timberlake

     feat_artist_name
2200      Duran Duran
         artist_id feat_artist_id  Number collaborations  \
4044  mn0000780265   mn0000129133                     25

               artist_name feat_artist_name
4044  Christina Rosenvinge      Nacho Vegas
        artist_id feat_artist_id  Number collaborations     artist_name  \
769  mn0000107949   mn0000130050                     10  Ismael Serrano

    feat_artist_name
769      Pasión Vega
         artist_id feat_artist_id  Number collaborations   artist_name  \
1614  mn0000224294   mn0000131627                     27  John Fogerty

                  feat_artist_name
1614  Creedence Clearwater Revival
         artist_id feat_artist_id  Number collaborations  artist_name  \
3010  mn0000531986   mn0000131650                     26  David Bowie

     feat_artist_name
3010    Talking Heads
        artist_id feat_artist_id  Number collaborations  artist_name  \
318  mn0000046861   mn0000137494                     24  Ray Charles

    feat_artist_name
318      Fats Domino
         artist_id feat_artist_id  Number collaborations      artist_name  \
2304  mn0000332141   mn0000137494                     35  Jerry Lee Lewis

     feat_artist_name
2304      Fats Domino
         artist_id feat_artist_id  Number collaborations artist_name  \
3402  mn0000619582   mn0000138235                      3  Alex Ubago

     feat_artist_name
3402    Laura Pausini
         artist_id feat_artist_id  Number collaborations artist_name  \
4519  mn0000861140   mn0000138235                     50         Nek

     feat_artist_name
4519    Laura Pausini
        artist_id feat_artist_id  Number collaborations     artist_name  \
770  mn0000107949   mn0000138672                     25  Ismael Serrano

       feat_artist_name
770  Joan Manuel Serrat
         artist_id feat_artist_id  Number collaborations     artist_name  \
1012  mn0000143559   mn0000138672                     26  Joaquín Sabina

        feat_artist_name
1012  Joan Manuel Serrat
         artist_id feat_artist_id  Number collaborations    artist_name  \
1207  mn0000172360   mn0000138672                     31  Víctor Manuel

        feat_artist_name
1207  Joan Manuel Serrat
        artist_id feat_artist_id  Number collaborations         artist_name  \
982  mn0000138672   mn0000143559                     49  Joan Manuel Serrat

    feat_artist_name
982   Joaquín Sabina
         artist_id feat_artist_id  Number collaborations artist_name  \
1063  mn0000150048   mn0002527545                      2      Enigma

     feat_artist_name
1063           Enigma
         artist_id feat_artist_id  Number collaborations      artist_name  \
1490  mn0000209142   mn0000151549                     41  George Harrison

      feat_artist_name
1490  Belinda Carlisle
         artist_id feat_artist_id  Number collaborations artist_name  \
1580  mn0000219203   mn0000154544                     62          U2

     feat_artist_name
1580        Green Day
         artist_id feat_artist_id  Number collaborations artist_name  \
4244  mn0000805274   mn0000157676                    142     Dr. Dre

     feat_artist_name
4244           Eminem

         artist_id feat_artist_id  Number collaborations   artist_name  \
1796  mn0000252978   mn0000159611                     26  Pedro Guerra

     feat_artist_name
1796             Bebe
         artist_id feat_artist_id  Number collaborations    artist_name  \
4345  mn0000831236   mn0000167517                    187  Mark Knopfler

     feat_artist_name
4345     Dire Straits
        artist_id feat_artist_id  Number collaborations artist_name  \
155  mn0000026061   mn0000172360                    102   Ana Belén

    feat_artist_name
155    Víctor Manuel
        artist_id feat_artist_id  Number collaborations         artist_name  \
983  mn0000138672   mn0000172360                     21  Joan Manuel Serrat

    feat_artist_name
983    Víctor Manuel
        artist_id feat_artist_id  Number collaborations   artist_name  \
448  mn0000069986   mn0000175286                     95  Kenny Rogers

    feat_artist_name
448     Dolly Parton
        artist_id feat_artist_id  Number collaborations artist_name  \
156  mn0000026061   mn0000175874                      5   Ana Belén

    feat_artist_name
156        Fito Páez
         artist_id feat_artist_id  Number collaborations     artist_name  \
3481  mn0000639397   mn0000175874                     57  Caetano Veloso

     feat_artist_name
3481        Fito Páez
        artist_id feat_artist_id  Number collaborations artist_name  \
208  mn0000031442   mn0000176358                     19   Anastacia

    feat_artist_name
208       Jamiroquai
         artist_id feat_artist_id  Number collaborations      artist_name  \
2306  mn0000332141   mn0000180228                     95  Jerry Lee Lewis

     feat_artist_name
2306    Elvis Presley
         artist_id feat_artist_id  Number collaborations    artist_name  \
3097  mn0000560453   mn0000183635                      2  Amaia Montero

     feat_artist_name
3097   Mikel Erentxun
         artist_id feat_artist_id  Number collaborations   artist_name  \
1616  mn0000224294   mn0000184043                      5  John Fogerty

     feat_artist_name
1616     Foo Fighters
         artist_id feat_artist_id  Number collaborations      artist_name  \
1698  mn0000234518   mn0000184502                     39  Louis Armstrong

     feat_artist_name
1698  Ella Fitzgerald
         artist_id feat_artist_id  Number collaborations     artist_name  \
3559  mn0000664817   mn0000186312                     31  Gloria Estefan

     feat_artist_name
3559       Celia Cruz
        artist_id feat_artist_id  Number collaborations artist_name  \
860  mn0000124492   mn0000187478                    240        Beck

    feat_artist_name
860     Eric Clapton
         artist_id feat_artist_id  Number collaborations      artist_name  \
1491  mn0000209142   mn0000187478                      5  George Harrison

     feat_artist_name
1491     Eric Clapton
         artist_id feat_artist_id  Number collaborations  artist_name  \
1564  mn0000217792   mn0000187478                     23  Ringo Starr

     feat_artist_name
1564     Eric Clapton
         artist_id feat_artist_id  Number collaborations    artist_name  \
2846  mn0000489303   mn0000187478                    116  The Yardbirds

     feat_artist_name
2846     Eric Clapton
         artist_id feat_artist_id  Number collaborations artist_name  \
3668  mn0000690254   mn0000187478                     16      ZZ Top

     feat_artist_name
3668     Eric Clapton
         artist_id feat_artist_id  Number collaborations    artist_name  \
3417  mn0000622805   mn0000200074                     31  Stevie Wonder

     feat_artist_name
3417    Lenny Kravitz
         artist_id feat_artist_id  Number collaborations  artist_name  \
4649  mn0000892823   mn0000200074                     10  Mick Jagger

     feat_artist_name
4649    Lenny Kravitz
         artist_id feat_artist_id  Number collaborations       artist_name  \
2218  mn0000314505   mn0000201760                      5  Vanessa Williams

     feat_artist_name
2218    George Benson
         artist_id feat_artist_id  Number collaborations artist_name  \
3277  mn0000606283   mn0000201760                    100  Al Jarreau

     feat_artist_name
3277    George Benson
         artist_id feat_artist_id  Number collaborations    artist_name  \
1453  mn0000201760   mn0001088078                    144  George Benson

     feat_artist_name
1453    George Benson
        artist_id feat_artist_id  Number collaborations   artist_name  \
501  mn0000074195   mn0000204386                     15  Natalie Cole

    feat_artist_name
501     James Taylor
         artist_id feat_artist_id  Number collaborations   artist_name  \
1461  mn0000204386   mn0000600069                     70  James Taylor
1466  mn0000204386   mn0001796334                     22  James Taylor

     feat_artist_name
1461     James Taylor
1466     James Taylor
         artist_id feat_artist_id  Number collaborations   artist_name  \
1461  mn0000204386   mn0000600069                     70  James Taylor
1466  mn0000204386   mn0001796334                     22  James Taylor

     feat_artist_name
1461     James Taylor
1466     James Taylor
         artist_id feat_artist_id  Number collaborations artist_name  \
1470  mn0000205970   mn0001217558                    136         Luz

     feat_artist_name
1470              Luz
         artist_id feat_artist_id  Number collaborations       artist_name  \
1066  mn0000151549   mn0000209142                     21  Belinda Carlisle

     feat_artist_name
1066  George Harrison
         artist_id feat_artist_id  Number collaborations   artist_name  \
1371  mn0000187478   mn0000209142                     51  Eric Clapton

     feat_artist_name
1371  George Harrison
         artist_id feat_artist_id  Number collaborations artist_name  \
1964  mn0000272689   mn0000210991                     88   Lil Wayne

     feat_artist_name
1964  Destiny's Child
         artist_id feat_artist_id  Number collaborations artist_name  \
3249  mn0000602378   mn0000210991                     13   Timbaland

     feat_artist_name
3249  Destiny's Child
         artist_id feat_artist_id  Number collaborations artist_name  \
4147  mn0000793848   mn0000217344                     12   Faithless

     feat_artist_name
4147             Dido
         artist_id feat_artist_id  Number collaborations   artist_name  \
1372  mn0000187478   mn0000217792                     20  Eric Clapton

     feat_artist_name
1372      Ringo Starr
         artist_id feat_artist_id  Number collaborations artist_name  \
1075  mn0000154544   mn0000219203                     44   Green Day

     feat_artist_name
1075               U2
         artist_id feat_artist_id  Number collaborations artist_name  \
2759  mn0000446509   mn0000219203                     16   Metallica

     feat_artist_name
2759               U2
         artist_id feat_artist_id  Number collaborations artist_name  \
2486  mn0000361014   mn0000224257                     62  Kanye West

     feat_artist_name
2486            Jay-Z
        artist_id feat_artist_id  Number collaborations  \
926  mn0000131627   mn0000224294                     16

                      artist_name feat_artist_name
926  Creedence Clearwater Revival     John Fogerty
         artist_id feat_artist_id  Number collaborations   artist_name  \
1301  mn0000184043   mn0000224294                     12  Foo Fighters

     feat_artist_name
1301     John Fogerty
         artist_id feat_artist_id  Number collaborations artist_name  \
1681  mn0000233066   mn0000224638                    155    Lou Reed

     feat_artist_name
1681        John Cale
         artist_id feat_artist_id  Number collaborations artist_name  \
3363  mn0000617196   mn0000224638                     25   Brian Eno

     feat_artist_name
3363        John Cale
         artist_id feat_artist_id  Number collaborations     artist_name  \
2598  mn0000380158   mn0000225369                     10  Noel Gallagher

     feat_artist_name
2598   Liam Gallagher
         artist_id feat_artist_id  Number collaborations    artist_name  \
1878  mn0000260212   mn0000227697                     63  Pet Shop Boys

     feat_artist_name
1878  Robbie Williams
         artist_id feat_artist_id  Number collaborations artist_name  \
3102  mn0000562850   mn0000227697                      3  Lily Allen

     feat_artist_name
3102  Robbie Williams
         artist_id feat_artist_id  Number collaborations artist_name  \
3307  mn0000609396   mn0000227697                     59   Tom Jones

     feat_artist_name
3307  Robbie Williams
         artist_id feat_artist_id  Number collaborations    artist_name  \
4019  mn0000776093   mn0000227697                     42  Kylie Minogue

     feat_artist_name
4019  Robbie Williams
        artist_id feat_artist_id  Number collaborations     artist_name  \
192  mn0000029884   mn0000232564                     46  Paul McCartney

    feat_artist_name
192      John Lennon
         artist_id feat_artist_id  Number collaborations  artist_name  \
3820  mn0000754032   mn0000232564                     88  The Beatles

     feat_artist_name
3820      John Lennon
         artist_id feat_artist_id  Number collaborations artist_name  \
1625  mn0000224638   mn0000233066                     92   John Cale

     feat_artist_name
1625         Lou Reed
         artist_id feat_artist_id  Number collaborations artist_name  \
2760  mn0000446509   mn0000233066                     53   Metallica

     feat_artist_name
2760         Lou Reed
         artist_id feat_artist_id  Number collaborations  artist_name  \
3012  mn0000531986   mn0000233066                      7  David Bowie

     feat_artist_name
3012         Lou Reed

         artist_id feat_artist_id  Number collaborations  \
4409  mn0000840402   mn0000233066                     77

                 artist_name feat_artist_name
4409  The Velvet Underground         Lou Reed
         artist_id feat_artist_id  Number collaborations      artist_name  \
1315  mn0000184502   mn0000234518                     42  Ella Fitzgerald

     feat_artist_name
1315  Louis Armstrong
        artist_id feat_artist_id  Number collaborations  artist_name  \
243  mn0000032438   mn0000237205                      2  Andrea Corr

    feat_artist_name
243          Madonna
         artist_id feat_artist_id  Number collaborations artist_name  \
2513  mn0000361541   mn0000237773                     11    Kasabian

     feat_artist_name
2513      Mark Ronson
         artist_id feat_artist_id  Number collaborations    artist_name  \
3434  mn0000627026   mn0000237773                      4  Amy Winehouse

     feat_artist_name
3434      Mark Ronson
       artist_id feat_artist_id  Number collaborations  artist_name  \
22  mn0000005307   mn0000239827                     21  Alicia Keys

   feat_artist_name
22       John Mayer
         artist_id feat_artist_id  Number collaborations      artist_name  \
1827  mn0000255733   mn0000243474                      7  Johnny Hallyday

     feat_artist_name
1827    Lionel Richie
         artist_id feat_artist_id  Number collaborations       artist_name  \
2067  mn0000291502   mn0000245250                     20  Juan Luis Guerra

     feat_artist_name
2067           Juanes
         artist_id feat_artist_id  Number collaborations    artist_name  \
4527  mn0000861687   mn0000245250                     14  Nelly Furtado

     feat_artist_name
4527           Juanes
         artist_id feat_artist_id  Number collaborations  artist_name  \
4633  mn0000892775   mn0000245250                     32  Miguel Bosé

     feat_artist_name
4633           Juanes
         artist_id feat_artist_id  Number collaborations     artist_name  \
3038  mn0000545074   mn0000246960                     33  George Michael

     feat_artist_name
3038            Wham!
        artist_id feat_artist_id  Number collaborations     artist_name  \
771  mn0000107949   mn0000252978                     13  Ismael Serrano

    feat_artist_name
771     Pedro Guerra
         artist_id feat_artist_id  Number collaborations artist_name  \
1107  mn0000159611   mn0000252978                     12        Bebe

     feat_artist_name
1107     Pedro Guerra
         artist_id feat_artist_id  Number collaborations artist_name  \
2138  mn0000299471   mn0000254556                     31   Scorpions

     feat_artist_name
2138     Roger Waters
       artist_id feat_artist_id  Number collaborations   artist_name  \
60  mn0000006334   mn0000255210                     49  Tony Bennett

   feat_artist_name
60      Diana Krall
        artist_id feat_artist_id  Number collaborations artist_name  \
660  mn0000089021   mn0000255733                      8  Jimmy Page

    feat_artist_name
660  Johnny Hallyday
         artist_id feat_artist_id  Number collaborations    artist_name  \
1765  mn0000243474   mn0000255733                      2  Lionel Richie

     feat_artist_name
1765  Johnny Hallyday
         artist_id feat_artist_id  Number collaborations       artist_name  \
4231  mn0000804476   mn0000255733                     18  Charles Aznavour

     feat_artist_name
4231  Johnny Hallyday
         artist_id feat_artist_id  Number collaborations         artist_name  \
2792  mn0000473554   mn0000258882                     10  Olivia Newton-John

     feat_artist_name
2792       Jon Secada
         artist_id feat_artist_id  Number collaborations     artist_name  \
3561  mn0000664817   mn0000258882                     13  Gloria Estefan

     feat_artist_name
3561       Jon Secada
         artist_id feat_artist_id  Number collaborations      artist_name  \
1639  mn0000227697   mn0000260212                     17  Robbie Williams

     feat_artist_name
1639    Pet Shop Boys
         artist_id feat_artist_id  Number collaborations  artist_name  \
3013  mn0000531986   mn0000260212                     38  David Bowie

     feat_artist_name
3013    Pet Shop Boys
         artist_id feat_artist_id  Number collaborations artist_name  \
2982  mn0000524821   mn0000260857                     15    Marlango

     feat_artist_name
2982    Jorge Drexler
         artist_id feat_artist_id  Number collaborations    artist_name  \
4682  mn0000903323   mn0000260857                      3  Jaime Urrutia

     feat_artist_name
4682    Jorge Drexler
         artist_id feat_artist_id  Number collaborations artist_name  \
4933  mn0001035294   mn0000266063                      6       Drake

     feat_artist_name
4933      Chris Brown
        artist_id feat_artist_id  Number collaborations artist_name  \
568  mn0000082482   mn0000268161                     12      Ketama

    feat_artist_name
568     Diego Torres
         artist_id feat_artist_id  Number collaborations     artist_name  \
3562  mn0000664817   mn0000271113                     27  Gloria Estefan

     feat_artist_name
3562   José Feliciano
         artist_id feat_artist_id  Number collaborations      artist_name  \
1504  mn0000210991   mn0000272689                      9  Destiny's Child

     feat_artist_name
1504        Lil Wayne
         artist_id feat_artist_id  Number collaborations artist_name  \
1781  mn0000245250   mn0000291502                     26      Juanes

      feat_artist_name
1781  Juan Luis Guerra
         artist_id feat_artist_id  Number collaborations     artist_name  \
3486  mn0000639397   mn0000292011                     28  Caetano Veloso

     feat_artist_name
3486   Roberto Carlos
       artist_id feat_artist_id  Number collaborations         artist_name  \
92  mn0000010904   mn0000295756                      3  Patricia Manterola

   feat_artist_name
92          Santana
         artist_id feat_artist_id  Number collaborations artist_name  \
3144  mn0000576718   mn0000295756                      4        Seal

     feat_artist_name
3144          Santana
         artist_id feat_artist_id  Number collaborations artist_name  \
3638  mn0000673621   mn0000296024                     17        Maná

     feat_artist_name
3638     Rubén Blades
         artist_id feat_artist_id  Number collaborations   artist_name  \
1805  mn0000254556   mn0000299471                     12  Roger Waters

     feat_artist_name
1805        Scorpions
         artist_id feat_artist_id  Number collaborations artist_name  \
2140  mn0000299471   mn0001626443                     31   Scorpions

     feat_artist_name
2140        Scorpions
         artist_id feat_artist_id  Number collaborations      artist_name  \
4289  mn0000815039   mn0000307461                    112  John Lee Hooker

     feat_artist_name
4289     Van Morrison
         artist_id feat_artist_id  Number collaborations         artist_name  \
4030  mn0000780258   mn0000312004                     12  Christina Aguilera

     feat_artist_name
4030       Luis Fonsi
         artist_id feat_artist_id  Number collaborations artist_name  \
4919  mn0001022592   mn0000312004                     10     Pitingo

     feat_artist_name
4919       Luis Fonsi
        artist_id feat_artist_id  Number collaborations  artist_name  \
901  mn0000128440   mn0000312890                     15  Duran Duran

      feat_artist_name
901  Justin Timberlake
        artist_id feat_artist_id  Number collaborations artist_name  \
360  mn0000052062   mn0000314505                      3    Chayanne

     feat_artist_name
360  Vanessa Williams
         artist_id feat_artist_id  Number collaborations    artist_name  \
1450  mn0000201760   mn0000314505                     19  George Benson

      feat_artist_name
1450  Vanessa Williams
         artist_id feat_artist_id  Number collaborations       artist_name  \
2229  mn0000314505   mn0002034784                     72  Vanessa Williams

      feat_artist_name
2229  Vanessa Williams

         artist_id feat_artist_id  Number collaborations artist_name  \
2368  mn0000346336   mn0000316834                    119  Pink Floyd

     feat_artist_name
2368      Marvin Gaye
         artist_id feat_artist_id  Number collaborations artist_name  \
3209  mn0000594665   mn0000316834                     81  Diana Ross

     feat_artist_name
3209      Marvin Gaye
       artist_id feat_artist_id  Number collaborations   artist_name  \
62  mn0000006334   mn0000317093                     29  Tony Bennett

   feat_artist_name
62    Nat King Cole
        artist_id feat_artist_id  Number collaborations artist_name  \
361  mn0000052062   mn0000317865                     20    Chayanne

    feat_artist_name
361   Jennifer Lopez
         artist_id feat_artist_id  Number collaborations   artist_name  \
3627  mn0000673486   mn0000317865                      3  Marc Anthony

     feat_artist_name
3627   Jennifer Lopez
         artist_id feat_artist_id  Number collaborations  artist_name  \
4651  mn0000892823   mn0000317865                     13  Mick Jagger

     feat_artist_name
4651   Jennifer Lopez
         artist_id feat_artist_id  Number collaborations     artist_name  \
3388  mn0000619388   mn0000329329                     13  Alejandro Sanz

     feat_artist_name
3388      Dani Martín
         artist_id feat_artist_id  Number collaborations artist_name  \
4970  mn0001502664   mn0000329329                      8       Leiva

     feat_artist_name
4970      Dani Martín
        artist_id feat_artist_id  Number collaborations  artist_name  \
813  mn0000120521   mn0000332141                     15  Chuck Berry

    feat_artist_name
813  Jerry Lee Lewis
        artist_id feat_artist_id  Number collaborations  artist_name  \
958  mn0000137494   mn0000332141                    175  Fats Domino

    feat_artist_name
958  Jerry Lee Lewis
         artist_id feat_artist_id  Number collaborations    artist_name  \
1255  mn0000180228   mn0000332141                     43  Elvis Presley

     feat_artist_name
1255  Jerry Lee Lewis
         artist_id feat_artist_id  Number collaborations  artist_name  \
4303  mn0000816890   mn0000332141                     10  Johnny Cash

     feat_artist_name
4303  Jerry Lee Lewis
         artist_id feat_artist_id  Number collaborations    artist_name  \
4020  mn0000776093   mn0000334193                     36  Kylie Minogue

     feat_artist_name
4020        New Order
         artist_id feat_artist_id  Number collaborations  artist_name  \
2235  mn0000316834   mn0000346336                     40  Marvin Gaye

     feat_artist_name
2235       Pink Floyd
         artist_id feat_artist_id  Number collaborations artist_name  \
2384  mn0000347151   mn0001324393                    107       Jewel

     feat_artist_name
2384            Jewel
         artist_id feat_artist_id  Number collaborations artist_name  \
4102  mn0000790797   mn0000350685                      5     Shakira

     feat_artist_name
4102          Pitbull
         artist_id feat_artist_id  Number collaborations   artist_name  \
2698  mn0000414251   mn0000354105                     42  Otis Redding

     feat_artist_name
2698     Jimi Hendrix
        artist_id feat_artist_id  Number collaborations artist_name  \
223  mn0000031685   mn0000354733                     25  Paul Simon

    feat_artist_name
223        Los Lobos
         artist_id feat_artist_id  Number collaborations  artist_name  \
4789  mn0000942680   mn0000354733                      7  Café Tacuba

     feat_artist_name
4789        Los Lobos
         artist_id feat_artist_id  Number collaborations  artist_name  \
3016  mn0000531986   mn0000355412                     72  David Bowie

     feat_artist_name
3016          Placebo
         artist_id feat_artist_id  Number collaborations artist_name  \
2459  mn0000357406   mn0000355142                     97     Nirvana

     feat_artist_name
2459          Nirvana
         artist_id feat_artist_id  Number collaborations artist_name  \
2986  mn0000525277   mn0000358214                     10   Ariel Rot

     feat_artist_name
2986     Los Ronaldos
         artist_id feat_artist_id  Number collaborations artist_name  \
1600  mn0000224257   mn0000361014                     51       Jay-Z

     feat_artist_name
1600       Kanye West
         artist_id feat_artist_id  Number collaborations artist_name  \
2508  mn0000361473   mn0001476617                      4   Kate Ryan
2509  mn0000361473   mn0002557083                      5   Kate Ryan

     feat_artist_name
2508        Kate Ryan
2509        Kate Ryan
         artist_id feat_artist_id  Number collaborations artist_name  \
2508  mn0000361473   mn0001476617                      4   Kate Ryan
2509  mn0000361473   mn0002557083                      5   Kate Ryan

     feat_artist_name
2508        Kate Ryan
2509        Kate Ryan
         artist_id feat_artist_id  Number collaborations  artist_name  \
1725  mn0000237773   mn0000361541                      5  Mark Ronson

     feat_artist_name
1725         Kasabian
        artist_id feat_artist_id  Number collaborations artist_name  \
130  mn0000021009   mn0000363307                      4       Slash

    feat_artist_name
130    Marta Sánchez
         artist_id feat_artist_id  Number collaborations   artist_name  \
4164  mn0000795360   mn0000363307                      9  Carlos Baute

     feat_artist_name
4164    Marta Sánchez
         artist_id feat_artist_id  Number collaborations     artist_name  \
4625  mn0000889126   mn0000363307                     26  Ricardo Arjona

     feat_artist_name
4625    Marta Sánchez
         artist_id feat_artist_id  Number collaborations artist_name  \
3315  mn0000609396   mn0000374126                     22   Tom Jones

       feat_artist_name
3315  Natalie Imbruglia
         artist_id feat_artist_id  Number collaborations  artist_name  \
3017  mn0000531986   mn0000378288                     35  David Bowie

     feat_artist_name
3017   Massive Attack
        artist_id feat_artist_id  Number collaborations artist_name  \
392  mn0000066915   mn0000379125                    228   Bob Dylan

    feat_artist_name
392       Neil Young
         artist_id feat_artist_id  Number collaborations          artist_name  \
4781  mn0000939567   mn0000379125                     72  Buffalo Springfield

     feat_artist_name
4781       Neil Young
         artist_id feat_artist_id  Number collaborations     artist_name  \
1633  mn0000225369   mn0000380158                      2  Liam Gallagher

     feat_artist_name
1633   Noel Gallagher
         artist_id feat_artist_id  Number collaborations artist_name  \
2639  mn0000393345   mn0000380158                     14       Oasis

     feat_artist_name
2639   Noel Gallagher
         artist_id feat_artist_id  Number collaborations  artist_name  \
4793  mn0000944700   mn0000391586                      5  Leona Lewis

     feat_artist_name
4793      James Blunt
         artist_id feat_artist_id  Number collaborations     artist_name  \
2600  mn0000380158   mn0000393345                      8  Noel Gallagher

     feat_artist_name
2600            Oasis
         artist_id feat_artist_id  Number collaborations artist_name  \
2656  mn0000402440   mn0000402920                     32     Raphael

     feat_artist_name
2656          Raphael
         artist_id feat_artist_id  Number collaborations    artist_name  \
2934  mn0000515395   mn0000402440                      2  Pastora Soler

     feat_artist_name
2934          Raphael
         artist_id feat_artist_id  Number collaborations artist_name  \
2955  mn0000522377   mn0000413524                     40       Sting

     feat_artist_name
2955       The Police
         artist_id feat_artist_id  Number collaborations   artist_name  \
2424  mn0000354105   mn0000414251                     69  Jimi Hendrix

     feat_artist_name
2424     Otis Redding
        artist_id feat_artist_id  Number collaborations  artist_name  \
319  mn0000046861   mn0000423829                     49  Ray Charles

    feat_artist_name
319      Miles Davis
         artist_id feat_artist_id  Number collaborations  artist_name  \
2874  mn0000492846   mn0000424078                     10  Miguel Ríos

     feat_artist_name
2874           Miliki
         artist_id feat_artist_id  Number collaborations   artist_name  \
4784  mn0000942595   mn0000424078                      7  Café Quijano

     feat_artist_name
4784           Miliki

         artist_id feat_artist_id  Number collaborations artist_name  \
1581  mn0000219203   mn0000446509                     19          U2

     feat_artist_name
1581        Metallica
         artist_id feat_artist_id  Number collaborations artist_name  \
1682  mn0000233066   mn0000446509                     48    Lou Reed

     feat_artist_name
1682        Metallica
         artist_id feat_artist_id  Number collaborations     artist_name  \
3565  mn0000664817   mn0000449578                     51  Gloria Estefan

         feat_artist_name
3565  Miami Sound Machine
        artist_id feat_artist_id  Number collaborations   artist_name  \
460  mn0000070929   mn0000467203                     29  The Jacksons

    feat_artist_name
460  Michael Jackson
        artist_id feat_artist_id  Number collaborations    artist_name  \
594  mn0000083013   mn0000467203                    201  The Jackson 5

    feat_artist_name
594  Michael Jackson
         artist_id feat_artist_id  Number collaborations artist_name  \
3210  mn0000594665   mn0000467203                     23  Diana Ross

     feat_artist_name
3210  Michael Jackson
         artist_id feat_artist_id  Number collaborations artist_name  \
1853  mn0000258882   mn0000473554                     12  Jon Secada

        feat_artist_name
1853  Olivia Newton-John
         artist_id feat_artist_id  Number collaborations artist_name  \
2804  mn0000476425   mn0000476649                     10        Mika
2806  mn0000476425   mn0001011359                      9        Mika
2808  mn0000476425   mn0001498488                     15        Mika
2812  mn0000476425   mn0002831086                     13        Mika
2813  mn0000476425   mn0003350483                      1        Mika

     feat_artist_name
2804             Mika
2806             Mika
2808             Mika
2812             Mika
2813             Mika
         artist_id feat_artist_id  Number collaborations artist_name  \
2804  mn0000476425   mn0000476649                     10        Mika
2806  mn0000476425   mn0001011359                      9        Mika
2808  mn0000476425   mn0001498488                     15        Mika
2812  mn0000476425   mn0002831086                     13        Mika
2813  mn0000476425   mn0003350483                      1        Mika

     feat_artist_name
2804             Mika
2806             Mika
2808             Mika
2812             Mika
2813             Mika
         artist_id feat_artist_id  Number collaborations artist_name  \
2804  mn0000476425   mn0000476649                     10        Mika
2806  mn0000476425   mn0001011359                      9        Mika
2808  mn0000476425   mn0001498488                     15        Mika
2812  mn0000476425   mn0002831086                     13        Mika
2813  mn0000476425   mn0003350483                      1        Mika

     feat_artist_name
2804             Mika
2806             Mika
2808             Mika
2812             Mika
2813             Mika
         artist_id feat_artist_id  Number collaborations artist_name  \
2804  mn0000476425   mn0000476649                     10        Mika
2806  mn0000476425   mn0001011359                      9        Mika
2808  mn0000476425   mn0001498488                     15        Mika
2812  mn0000476425   mn0002831086                     13        Mika
2813  mn0000476425   mn0003350483                      1        Mika

     feat_artist_name
2804             Mika
2806             Mika
2808             Mika
2812             Mika
2813             Mika
         artist_id feat_artist_id  Number collaborations artist_name  \
2804  mn0000476425   mn0000476649                     10        Mika
2806  mn0000476425   mn0001011359                      9        Mika
2808  mn0000476425   mn0001498488                     15        Mika
2812  mn0000476425   mn0002831086                     13        Mika
2813  mn0000476425   mn0003350483                      1        Mika

     feat_artist_name
2804             Mika
2806             Mika
2808             Mika
2812             Mika
2813             Mika
         artist_id feat_artist_id  Number collaborations   artist_name  \
1379  mn0000187478   mn0000489303                     42  Eric Clapton

     feat_artist_name
1379    The Yardbirds
        artist_id feat_artist_id  Number collaborations artist_name  \
159  mn0000026061   mn0000492846                     69   Ana Belén

    feat_artist_name
159      Miguel Ríos
         artist_id feat_artist_id  Number collaborations artist_name  \
2737  mn0000424078   mn0000492846                      6      Miliki

     feat_artist_name
2737      Miguel Ríos
        artist_id feat_artist_id  Number collaborations artist_name  \
571  mn0000082482   mn0000494368                     11      Ketama

    feat_artist_name
571     Antonio Vega
        artist_id feat_artist_id  Number collaborations artist_name  \
572  mn0000082482   mn0000494672                      3      Ketama

    feat_artist_name
572   Antonio Flores
        artist_id feat_artist_id  Number collaborations        artist_name  \
270  mn0000038936   mn0000504815                     70  Simon & Garfunkel

    feat_artist_name
270    Art Garfunkel
        artist_id feat_artist_id  Number collaborations     artist_name  \
750  mn0000102985   mn0000504815                     37  Julio Iglesias

    feat_artist_name
750    Art Garfunkel
         artist_id feat_artist_id  Number collaborations artist_name  \
2657  mn0000402440   mn0000515395                     20     Raphael

     feat_artist_name
2657    Pastora Soler
         artist_id feat_artist_id  Number collaborations     artist_name  \
3391  mn0000619388   mn0000515395                     23  Alejandro Sanz

     feat_artist_name
3391    Pastora Soler
         artist_id feat_artist_id  Number collaborations artist_name  \
3587  mn0000669014   mn0000515395                      6        Malú

     feat_artist_name
3587    Pastora Soler
         artist_id feat_artist_id  Number collaborations       artist_name  \
5097  mn0002562509   mn0000515395                      4  David Bustamante

     feat_artist_name
5097    Pastora Soler
         artist_id feat_artist_id  Number collaborations     artist_name  \
3117  mn0000567809   mn0000516929                     10  Modern Talking

     feat_artist_name
3117           *NSYNC
         artist_id feat_artist_id  Number collaborations artist_name  \
2683  mn0000413524   mn0000522377                     79  The Police

     feat_artist_name
2683            Sting
         artist_id feat_artist_id  Number collaborations artist_name  \
4227  mn0000802018   mn0000522430                      4     Chambao

     feat_artist_name
4227           Camila
         artist_id feat_artist_id  Number collaborations artist_name  \
4461  mn0000852855   mn0000524050                    131  Roxy Music

     feat_artist_name
4461      Bryan Ferry
         artist_id feat_artist_id  Number collaborations    artist_name  \
1894  mn0000260857   mn0000524821                     25  Jorge Drexler

     feat_artist_name
1894         Marlango
         artist_id feat_artist_id  Number collaborations   artist_name  \
2462  mn0000358214   mn0000525277                      3  Los Ronaldos

     feat_artist_name
2462        Ariel Rot
         artist_id feat_artist_id  Number collaborations      artist_name  \
4210  mn0000797932   mn0000525277                     26  Enrique Bunbury

     feat_artist_name
4210        Ariel Rot
         artist_id feat_artist_id  Number collaborations artist_name  \
4445  mn0000846787   mn0000525277                      6      Pereza

     feat_artist_name
4445        Ariel Rot
         artist_id feat_artist_id  Number collaborations    artist_name  \
4683  mn0000903323   mn0000525277                      8  Jaime Urrutia

     feat_artist_name
4683        Ariel Rot
         artist_id feat_artist_id  Number collaborations     artist_name  \
5036  mn0002009120   mn0000525277                      1  The Cabriolets

     feat_artist_name
5036        Ariel Rot
        artist_id feat_artist_id  Number collaborations    artist_name  \
928  mn0000131650   mn0000531986                      5  Talking Heads

    feat_artist_name
928      David Bowie
         artist_id feat_artist_id  Number collaborations artist_name  \
1683  mn0000233066   mn0000531986                     32    Lou Reed

     feat_artist_name
1683      David Bowie
         artist_id feat_artist_id  Number collaborations    artist_name  \
1883  mn0000260212   mn0000531986                     23  Pet Shop Boys

     feat_artist_name
1883      David Bowie
         artist_id feat_artist_id  Number collaborations artist_name  \
2453  mn0000355412   mn0000531986                      5     Placebo

     feat_artist_name
2453      David Bowie
         artist_id feat_artist_id  Number collaborations     artist_name  \
2557  mn0000378288   mn0000531986                      2  Massive Attack

     feat_artist_name
2557      David Bowie

         artist_id feat_artist_id  Number collaborations artist_name  \
4499  mn0000858827   mn0000531986                      5       Queen

     feat_artist_name
4499      David Bowie
         artist_id feat_artist_id  Number collaborations artist_name  \
4715  mn0000926548   mn0000531986                     45    Iggy Pop

     feat_artist_name
4715      David Bowie
         artist_id feat_artist_id  Number collaborations   artist_name  \
3457  mn0000635848   mn0000536894                      4  David Bisbal

     feat_artist_name
3457     David Civera
         artist_id feat_artist_id  Number collaborations artist_name  \
1792  mn0000246960   mn0000545074                     48       Wham!

     feat_artist_name
1792   George Michael
         artist_id feat_artist_id  Number collaborations artist_name  \
4196  mn0000796734   mn0000545074                     76  Elton John

     feat_artist_name
4196   George Michael
         artist_id feat_artist_id  Number collaborations artist_name  \
4500  mn0000858827   mn0000545074                     10       Queen

     feat_artist_name
4500   George Michael
         artist_id feat_artist_id  Number collaborations      artist_name  \
4739  mn0000927555   mn0000545074                      6  Aretha Franklin

     feat_artist_name
4739   George Michael
         artist_id feat_artist_id  Number collaborations  artist_name  \
3068  mn0000551762   mn0000548397                     10  Miley Cyrus

     feat_artist_name
3068   Jonas Brothers
         artist_id feat_artist_id  Number collaborations  artist_name  \
4888  mn0000996127   mn0000548397                      6  Demi Lovato

     feat_artist_name
4888   Jonas Brothers
         artist_id feat_artist_id  Number collaborations     artist_name  \
3062  mn0000548397   mn0000551762                      7  Jonas Brothers

     feat_artist_name
3062      Miley Cyrus
         artist_id feat_artist_id  Number collaborations   artist_name  \
3458  mn0000635848   mn0000551762                     19  David Bisbal

     feat_artist_name
3458      Miley Cyrus
         artist_id feat_artist_id  Number collaborations     artist_name  \
1298  mn0000183635   mn0000560453                     13  Mikel Erentxun

     feat_artist_name
1298    Amaia Montero
         artist_id feat_artist_id  Number collaborations      artist_name  \
1642  mn0000227697   mn0000562850                     15  Robbie Williams

     feat_artist_name
1642       Lily Allen
         artist_id feat_artist_id  Number collaborations artist_name  \
4487  mn0000857621   mn0000562850                      2       Keane

     feat_artist_name
4487       Lily Allen
         artist_id feat_artist_id  Number collaborations artist_name  \
2943  mn0000516929   mn0000567809                     30      *NSYNC

     feat_artist_name
2943   Modern Talking
         artist_id feat_artist_id  Number collaborations artist_name  \
2113  mn0000295756   mn0000576718                     15     Santana

     feat_artist_name
2113             Seal
         artist_id feat_artist_id  Number collaborations artist_name  \
3253  mn0000602378   mn0000578999                      2   Timbaland

     feat_artist_name
3253          Aaliyah
        artist_id feat_artist_id  Number collaborations artist_name  \
229  mn0000031685   mn0000585249                     20  Paul Simon

    feat_artist_name
229     Annie Lennox
         artist_id feat_artist_id  Number collaborations  artist_name  \
2238  mn0000316834   mn0000594665                     49  Marvin Gaye

     feat_artist_name
2238       Diana Ross
         artist_id feat_artist_id  Number collaborations      artist_name  \
2777  mn0000467203   mn0000594665                     10  Michael Jackson

     feat_artist_name
2777       Diana Ross
         artist_id feat_artist_id  Number collaborations artist_name  \
4681  mn0000899530   mn0000597094                     83  The Smiths

     feat_artist_name
4681        Morrissey
         artist_id feat_artist_id  Number collaborations artist_name  \
3316  mn0000609396   mn0000597309                     24   Tom Jones

     feat_artist_name
3316      Tina Turner
         artist_id feat_artist_id  Number collaborations artist_name  \
3229  mn0000600435   mn0001341367                      8        Aqua

     feat_artist_name
3229             Aqua
        artist_id feat_artist_id  Number collaborations artist_name  \
211  mn0000031442   mn0000601079                     25   Anastacia

    feat_artist_name
211  Eros Ramazzotti
        artist_id feat_artist_id  Number collaborations     artist_name  \
753  mn0000102985   mn0000601079                     71  Julio Iglesias

    feat_artist_name
753  Eros Ramazzotti
        artist_id feat_artist_id  Number collaborations artist_name  \
764  mn0000107090   mn0000601079                     14        Cher

    feat_artist_name
764  Eros Ramazzotti
        artist_id feat_artist_id  Number collaborations         artist_name  \
741  mn0000101072   mn0000602378                     11  The Pussycat Dolls

    feat_artist_name
741        Timbaland
         artist_id feat_artist_id  Number collaborations      artist_name  \
1507  mn0000210991   mn0000602378                     14  Destiny's Child

     feat_artist_name
1507        Timbaland
         artist_id feat_artist_id  Number collaborations artist_name  \
3166  mn0000578999   mn0000602378                      4     Aaliyah

     feat_artist_name
3166        Timbaland
        artist_id feat_artist_id  Number collaborations  artist_name  \
649  mn0000088035   mn0000606283                      6  Kelly Price

    feat_artist_name
649       Al Jarreau
         artist_id feat_artist_id  Number collaborations    artist_name  \
1451  mn0000201760   mn0000606283                     18  George Benson

     feat_artist_name
1451       Al Jarreau
         artist_id feat_artist_id  Number collaborations    artist_name  \
4280  mn0000810166   mn0000607448                     16  Vonda Shepard

     feat_artist_name
4280         Al Green
         artist_id feat_artist_id  Number collaborations      artist_name  \
1643  mn0000227697   mn0000609396                     61  Robbie Williams

     feat_artist_name
1643        Tom Jones
         artist_id feat_artist_id  Number collaborations        artist_name  \
2538  mn0000374126   mn0000609396                      2  Natalie Imbruglia

     feat_artist_name
2538        Tom Jones
         artist_id feat_artist_id  Number collaborations  artist_name  \
3224  mn0000597309   mn0000609396                     28  Tina Turner

     feat_artist_name
3224        Tom Jones
         artist_id feat_artist_id  Number collaborations    artist_name  \
3476  mn0000636433   mn0000609396                     26  The Cardigans

     feat_artist_name
3476        Tom Jones
         artist_id feat_artist_id  Number collaborations      artist_name  \
3525  mn0000659277   mn0000610166                     26  Franco Battiato

     feat_artist_name
3525    Tiziano Ferro
         artist_id feat_artist_id  Number collaborations artist_name  \
1627  mn0000224638   mn0000617196                     76   John Cale

     feat_artist_name
1627        Brian Eno
         artist_id feat_artist_id  Number collaborations  artist_name  \
4638  mn0000892775   mn0000617613                     28  Miguel Bosé

         feat_artist_name
4638  Alejandro Fernández
        artist_id feat_artist_id  Number collaborations artist_name  \
517  mn0000075591   mn0000619388                     23   The Corrs

    feat_artist_name
517   Alejandro Sanz
         artist_id feat_artist_id  Number collaborations  artist_name  \
2298  mn0000329329   mn0000619388                      1  Dani Martín

     feat_artist_name
2298   Alejandro Sanz
         artist_id feat_artist_id  Number collaborations    artist_name  \
2935  mn0000515395   mn0000619388                     12  Pastora Soler

     feat_artist_name
2935   Alejandro Sanz
         artist_id feat_artist_id  Number collaborations artist_name  \
4106  mn0000790797   mn0000619388                     22     Shakira

     feat_artist_name
4106   Alejandro Sanz
        artist_id feat_artist_id  Number collaborations    artist_name  \
970  mn0000138235   mn0000619582                     26  Laura Pausini

    feat_artist_name
970       Alex Ubago
         artist_id feat_artist_id  Number collaborations   artist_name  \
5032  mn0001976997   mn0000622555                      2  Sole Giménez

      feat_artist_name
5032  Seguridad Social
         artist_id feat_artist_id  Number collaborations    artist_name  \
1435  mn0000200074   mn0000622805                     13  Lenny Kravitz

     feat_artist_name
1435    Stevie Wonder
         artist_id feat_artist_id  Number collaborations     artist_name  \
3796  mn0000751613   mn0000622805                     63  Andrea Bocelli

     feat_artist_name
3796    Stevie Wonder
         artist_id feat_artist_id  Number collaborations  artist_name  \
1730  mn0000237773   mn0000627026                      1  Mark Ronson

     feat_artist_name
1730    Amy Winehouse
         artist_id feat_artist_id  Number collaborations   artist_name  \
3031  mn0000536894   mn0000635848                      4  David Civera

     feat_artist_name
3031     David Bisbal
         artist_id feat_artist_id  Number collaborations  artist_name  \
3070  mn0000551762   mn0000635848                     13  Miley Cyrus

     feat_artist_name
3070     David Bisbal
         artist_id feat_artist_id  Number collaborations artist_name  \
3543  mn0000664144   mn0000635848                      6      Gisela

     feat_artist_name
3543     David Bisbal
         artist_id feat_artist_id  Number collaborations    artist_name  \
5114  mn0002641990   mn0000635848                      2  Pablo Alborán

     feat_artist_name
5114     David Bisbal
         artist_id feat_artist_id  Number collaborations artist_name  \
3317  mn0000609396   mn0000636433                     12   Tom Jones

     feat_artist_name
3317    The Cardigans
        artist_id feat_artist_id  Number collaborations artist_name  \
573  mn0000082482   mn0000639397                     12      Ketama

    feat_artist_name
573   Caetano Veloso
         artist_id feat_artist_id  Number collaborations artist_name  \
1231  mn0000175874   mn0000639397                     21   Fito Páez

     feat_artist_name
1231   Caetano Veloso
         artist_id feat_artist_id  Number collaborations     artist_name  \
2081  mn0000292011   mn0000639397                    207  Roberto Carlos

     feat_artist_name
2081   Caetano Veloso
         artist_id feat_artist_id  Number collaborations   artist_name  \
3509  mn0000652255   mn0000639397                    222  Gilberto Gil

     feat_artist_name
3509   Caetano Veloso

         artist_id feat_artist_id  Number collaborations     artist_name  \
3490  mn0000639397   mn0000652255                    146  Caetano Veloso

     feat_artist_name
3490     Gilberto Gil
         artist_id feat_artist_id  Number collaborations    artist_name  \
3332  mn0000610166   mn0000659277                     43  Tiziano Ferro

     feat_artist_name
3332  Franco Battiato
         artist_id feat_artist_id  Number collaborations   artist_name  \
3460  mn0000635848   mn0000664144                     26  David Bisbal

     feat_artist_name
3460           Gisela
         artist_id feat_artist_id  Number collaborations artist_name  \
4006  mn0000775966   mn0000664144                     12      Chenoa

     feat_artist_name
4006           Gisela
         artist_id feat_artist_id  Number collaborations artist_name  \
1357  mn0000186312   mn0000664817                     55  Celia Cruz

     feat_artist_name
1357   Gloria Estefan
         artist_id feat_artist_id  Number collaborations artist_name  \
1854  mn0000258882   mn0000664817                     15  Jon Secada

     feat_artist_name
1854   Gloria Estefan
         artist_id feat_artist_id  Number collaborations     artist_name  \
1955  mn0000271113   mn0000664817                     24  José Feliciano

     feat_artist_name
1955   Gloria Estefan
         artist_id feat_artist_id  Number collaborations          artist_name  \
2770  mn0000449578   mn0000664817                     13  Miami Sound Machine

     feat_artist_name
2770   Gloria Estefan
         artist_id feat_artist_id  Number collaborations    artist_name  \
2937  mn0000515395   mn0000669014                      3  Pastora Soler

     feat_artist_name
2937             Malú
         artist_id feat_artist_id  Number collaborations      artist_name  \
3607  mn0000672123   mn0000669014                     10  Manuel Carrasco

     feat_artist_name
3607             Malú
         artist_id feat_artist_id  Number collaborations artist_name  \
3591  mn0000669014   mn0000672123                     14        Malú

     feat_artist_name
3591  Manuel Carrasco
         artist_id feat_artist_id  Number collaborations artist_name  \
4007  mn0000775966   mn0000672123                     14      Chenoa

     feat_artist_name
4007  Manuel Carrasco
         artist_id feat_artist_id  Number collaborations     artist_name  \
2263  mn0000317865   mn0000673486                     22  Jennifer Lopez

     feat_artist_name
2263     Marc Anthony
         artist_id feat_artist_id  Number collaborations     artist_name  \
4627  mn0000889126   mn0000673486                     11  Ricardo Arjona

     feat_artist_name
4627     Marc Anthony
         artist_id feat_artist_id  Number collaborations   artist_name  \
2125  mn0000296024   mn0000673621                     28  Rubén Blades

     feat_artist_name
2125             Maná
         artist_id feat_artist_id  Number collaborations   artist_name  \
1381  mn0000187478   mn0000690254                     61  Eric Clapton

     feat_artist_name
1381           ZZ Top
         artist_id feat_artist_id  Number collaborations       artist_name  \
4235  mn0000804476   mn0000745915                     61  Charles Aznavour

     feat_artist_name
4235        Paul Anka
         artist_id feat_artist_id  Number collaborations  artist_name  \
4641  mn0000892775   mn0000750024                     72  Miguel Bosé

     feat_artist_name
4641      Ana Torroja
        artist_id feat_artist_id  Number collaborations artist_name  \
424  mn0000068934   mn0000751613                     84     Kenny G

    feat_artist_name
424   Andrea Bocelli
         artist_id feat_artist_id  Number collaborations    artist_name  \
3424  mn0000622805   mn0000751613                     35  Stevie Wonder

     feat_artist_name
3424   Andrea Bocelli
        artist_id feat_artist_id  Number collaborations     artist_name  \
194  mn0000029884   mn0000754032                     64  Paul McCartney

    feat_artist_name
194      The Beatles
         artist_id feat_artist_id  Number collaborations  artist_name  \
1678  mn0000232564   mn0000754032                     28  John Lennon

     feat_artist_name
1678      The Beatles
         artist_id feat_artist_id  Number collaborations artist_name  \
4860  mn0000988471   mn0000756180                      3        Enya

     feat_artist_name
4860  Sinéad O'Connor
        artist_id feat_artist_id  Number collaborations   artist_name  \
847  mn0000122754   mn0000757085                     10  Cyndi Lauper

    feat_artist_name
847          Bangles
         artist_id feat_artist_id  Number collaborations  artist_name  \
4655  mn0000892823   mn0000767068                     28  Mick Jagger

     feat_artist_name
4655   Keith Richards
         artist_id feat_artist_id  Number collaborations         artist_name  \
4669  mn0000894465   mn0000767068                     11  The Rolling Stones

     feat_artist_name
4669   Keith Richards
        artist_id feat_artist_id  Number collaborations   artist_name  \
809  mn0000116178   mn0000771470                     54  Culture Club

    feat_artist_name
809       Boy George
         artist_id feat_artist_id  Number collaborations  artist_name  \
4643  mn0000892775   mn0000773147                     23  Miguel Bosé

     feat_artist_name
4643   Chavela Vargas
         artist_id feat_artist_id  Number collaborations    artist_name  \
4619  mn0000885569   mn0000775323                     28  Michael Bublé

     feat_artist_name
4619      Chris Isaak
         artist_id feat_artist_id  Number collaborations artist_name  \
3545  mn0000664144   mn0000775966                      2      Gisela

     feat_artist_name
3545           Chenoa
         artist_id feat_artist_id  Number collaborations      artist_name  \
3608  mn0000672123   mn0000775966                     16  Manuel Carrasco

     feat_artist_name
3608           Chenoa
         artist_id feat_artist_id  Number collaborations   artist_name  \
4820  mn0000950726   mn0000775966                     14  Gloria Trevi

     feat_artist_name
4820           Chenoa
         artist_id feat_artist_id  Number collaborations      artist_name  \
1645  mn0000227697   mn0000776093                     25  Robbie Williams

     feat_artist_name
1645    Kylie Minogue
         artist_id feat_artist_id  Number collaborations artist_name  \
2322  mn0000334193   mn0000776093                     20   New Order

     feat_artist_name
2322    Kylie Minogue
         artist_id feat_artist_id  Number collaborations artist_name  \
2190  mn0000312004   mn0000780258                     30  Luis Fonsi

        feat_artist_name
2190  Christina Aguilera
        artist_id feat_artist_id  Number collaborations  artist_name  \
908  mn0000129133   mn0000780265                     41  Nacho Vegas

         feat_artist_name
908  Christina Rosenvinge
         artist_id feat_artist_id  Number collaborations artist_name  \
4446  mn0000846787   mn0000780265                      7      Pereza

          feat_artist_name
4446  Christina Rosenvinge
         artist_id feat_artist_id  Number collaborations     artist_name  \
4086  mn0000785500   mn0000915816                     20  James Morrison

     feat_artist_name
4086   James Morrison
         artist_id feat_artist_id  Number collaborations artist_name  \
2397  mn0000350685   mn0000790797                     18     Pitbull

     feat_artist_name
2397          Shakira
         artist_id feat_artist_id  Number collaborations     artist_name  \
3395  mn0000619388   mn0000790797                     28  Alejandro Sanz

     feat_artist_name
3395          Shakira
         artist_id feat_artist_id  Number collaborations artist_name  \
1557  mn0000217344   mn0000793848                     19        Dido

     feat_artist_name
1557        Faithless
         artist_id feat_artist_id  Number collaborations    artist_name  \
2518  mn0000363307   mn0000795360                     16  Marta Sánchez

     feat_artist_name
2518     Carlos Baute
       artist_id feat_artist_id  Number collaborations   artist_name  \
69  mn0000006334   mn0000796734                     43  Tony Bennett

   feat_artist_name
69       Elton John
         artist_id feat_artist_id  Number collaborations     artist_name  \
3042  mn0000545074   mn0000796734                     25  George Michael

     feat_artist_name
3042       Elton John
         artist_id feat_artist_id  Number collaborations artist_name  \
2987  mn0000525277   mn0000797932                      6   Ariel Rot

     feat_artist_name
2987  Enrique Bunbury
         artist_id feat_artist_id  Number collaborations    artist_name  \
4684  mn0000903323   mn0000797932                     18  Jaime Urrutia

     feat_artist_name
4684  Enrique Bunbury
         artist_id feat_artist_id  Number collaborations artist_name  \
2969  mn0000522430   mn0000802018                      2      Camila

     feat_artist_name
2969          Chambao
         artist_id feat_artist_id  Number collaborations      artist_name  \
1832  mn0000255733   mn0000804476                     59  Johnny Hallyday

      feat_artist_name
1832  Charles Aznavour
         artist_id feat_artist_id  Number collaborations artist_name  \
3748  mn0000745915   mn0000804476                     76   Paul Anka

      feat_artist_name
3748  Charles Aznavour
         artist_id feat_artist_id  Number collaborations artist_name  \
1091  mn0000157676   mn0000805274                    191      Eminem

     feat_artist_name
1091          Dr. Dre
        artist_id feat_artist_id  Number collaborations artist_name  \
161  mn0000026061   mn0000805858                     19   Ana Belén

    feat_artist_name
161           Estopa

        artist_id feat_artist_id  Number collaborations artist_name  \
213  mn0000031442   mn0000810166                      9   Anastacia

    feat_artist_name
213    Vonda Shepard
         artist_id feat_artist_id  Number collaborations artist_name  \
3296  mn0000607448   mn0000810166                     33    Al Green

     feat_artist_name
3296    Vonda Shepard
         artist_id feat_artist_id  Number collaborations   artist_name  \
2176  mn0000307461   mn0000815039                     20  Van Morrison

     feat_artist_name
2176  John Lee Hooker
        artist_id feat_artist_id  Number collaborations artist_name  \
395  mn0000066915   mn0000816890                     51   Bob Dylan

    feat_artist_name
395      Johnny Cash
         artist_id feat_artist_id  Number collaborations      artist_name  \
2313  mn0000332141   mn0000816890                     68  Jerry Lee Lewis

     feat_artist_name
2313      Johnny Cash
        artist_id feat_artist_id  Number collaborations artist_name  \
667  mn0000089021   mn0000830538                    121  Jimmy Page

    feat_artist_name
667     Robert Plant
         artist_id feat_artist_id  Number collaborations   artist_name  \
1184  mn0000167517   mn0000831236                    117  Dire Straits

     feat_artist_name
1184    Mark Knopfler
        artist_id feat_artist_id  Number collaborations artist_name  \
780  mn0000108323   mn0000836376                      5        Coti

    feat_artist_name
780  Julieta Venegas
         artist_id feat_artist_id  Number collaborations artist_name  \
1688  mn0000233066   mn0000840402                     92    Lou Reed

            feat_artist_name
1688  The Velvet Underground
        artist_id feat_artist_id  Number collaborations artist_name  \
781  mn0000108323   mn0000846787                      1        Coti

    feat_artist_name
781           Pereza
         artist_id feat_artist_id  Number collaborations artist_name  \
2988  mn0000525277   mn0000846787                     14   Ariel Rot

     feat_artist_name
2988           Pereza
         artist_id feat_artist_id  Number collaborations  \
4045  mn0000780265   mn0000846787                     10

               artist_name feat_artist_name
4045  Christina Rosenvinge           Pereza
         artist_id feat_artist_id  Number collaborations  artist_name  \
5024  mn0001890380   mn0000846787                      3  Coque Malla

     feat_artist_name
5024           Pereza
         artist_id feat_artist_id  Number collaborations  artist_name  \
2975  mn0000524050   mn0000852855                    215  Bryan Ferry

     feat_artist_name
2975       Roxy Music
         artist_id feat_artist_id  Number collaborations artist_name  \
3106  mn0000562850   mn0000857621                      4  Lily Allen

     feat_artist_name
3106            Keane
         artist_id feat_artist_id  Number collaborations  artist_name  \
3026  mn0000531986   mn0000858827                     16  David Bowie

     feat_artist_name
3026            Queen
         artist_id feat_artist_id  Number collaborations     artist_name  \
3043  mn0000545074   mn0000858827                     63  George Michael

     feat_artist_name
3043            Queen
         artist_id feat_artist_id  Number collaborations artist_name  \
4972  mn0001502664   mn0000859026                      4       Leiva

        feat_artist_name
4972  Natalia Lafourcade
        artist_id feat_artist_id  Number collaborations    artist_name  \
976  mn0000138235   mn0000861140                     69  Laura Pausini

    feat_artist_name
976              Nek
         artist_id feat_artist_id  Number collaborations artist_name  \
1785  mn0000245250   mn0000861687                     16      Juanes

     feat_artist_name
1785    Nelly Furtado
         artist_id feat_artist_id  Number collaborations    artist_name  \
4621  mn0000885569   mn0000861687                      2  Michael Bublé

     feat_artist_name
4621    Nelly Furtado
        artist_id feat_artist_id  Number collaborations     artist_name  \
879  mn0000127967   mn0000862671                      1  Antonio Orozco

    feat_artist_name
879     Lucie Silvas
       artist_id feat_artist_id  Number collaborations    artist_name  \
76  mn0000006855   mn0000869068                     28  Pablo Milanés

   feat_artist_name
76    Mercedes Sosa
         artist_id feat_artist_id  Number collaborations  artist_name  \
3987  mn0000775323   mn0000885569                     24  Chris Isaak

     feat_artist_name
3987    Michael Bublé
         artist_id feat_artist_id  Number collaborations    artist_name  \
4538  mn0000861687   mn0000885569                      1  Nelly Furtado

     feat_artist_name
4538    Michael Bublé
         artist_id feat_artist_id  Number collaborations    artist_name  \
2519  mn0000363307   mn0000889126                     13  Marta Sánchez

     feat_artist_name
2519   Ricardo Arjona
         artist_id feat_artist_id  Number collaborations   artist_name  \
3632  mn0000673486   mn0000889126                      6  Marc Anthony

     feat_artist_name
3632   Ricardo Arjona
         artist_id feat_artist_id  Number collaborations artist_name  \
1786  mn0000245250   mn0000892775                     11      Juanes

     feat_artist_name
1786      Miguel Bosé
         artist_id feat_artist_id  Number collaborations          artist_name  \
3378  mn0000617613   mn0000892775                     14  Alejandro Fernández

     feat_artist_name
3378      Miguel Bosé
         artist_id feat_artist_id  Number collaborations  artist_name  \
3772  mn0000750024   mn0000892775                     64  Ana Torroja

     feat_artist_name
3772      Miguel Bosé
         artist_id feat_artist_id  Number collaborations     artist_name  \
3978  mn0000773147   mn0000892775                     17  Chavela Vargas

     feat_artist_name
3978      Miguel Bosé
         artist_id feat_artist_id  Number collaborations    artist_name  \
1437  mn0000200074   mn0000892823                     64  Lenny Kravitz

     feat_artist_name
1437      Mick Jagger
         artist_id feat_artist_id  Number collaborations     artist_name  \
2268  mn0000317865   mn0000892823                     19  Jennifer Lopez

     feat_artist_name
2268      Mick Jagger
         artist_id feat_artist_id  Number collaborations     artist_name  \
3901  mn0000767068   mn0000892823                     50  Keith Richards

     feat_artist_name
3901      Mick Jagger
         artist_id feat_artist_id  Number collaborations         artist_name  \
4671  mn0000894465   mn0000892823                    102  The Rolling Stones

     feat_artist_name
4671      Mick Jagger
         artist_id feat_artist_id  Number collaborations     artist_name  \
3902  mn0000767068   mn0000894465                     30  Keith Richards

        feat_artist_name
3902  The Rolling Stones
         artist_id feat_artist_id  Number collaborations  artist_name  \
4656  mn0000892823   mn0000894465                     48  Mick Jagger

        feat_artist_name
4656  The Rolling Stones
         artist_id feat_artist_id  Number collaborations artist_name  \
3219  mn0000597094   mn0000899530                    145   Morrissey

     feat_artist_name
3219       The Smiths
         artist_id feat_artist_id  Number collaborations    artist_name  \
1896  mn0000260857   mn0000903323                     11  Jorge Drexler

     feat_artist_name
1896    Jaime Urrutia
         artist_id feat_artist_id  Number collaborations artist_name  \
2989  mn0000525277   mn0000903323                      2   Ariel Rot

     feat_artist_name
2989    Jaime Urrutia
         artist_id feat_artist_id  Number collaborations      artist_name  \
4211  mn0000797932   mn0000903323                     67  Enrique Bunbury

     feat_artist_name
4211    Jaime Urrutia
         artist_id feat_artist_id  Number collaborations  artist_name  \
3027  mn0000531986   mn0000926548                     62  David Bowie

     feat_artist_name
3027         Iggy Pop
        artist_id feat_artist_id  Number collaborations  artist_name  \
325  mn0000046861   mn0000927555                     29  Ray Charles

    feat_artist_name
325  Aretha Franklin
         artist_id feat_artist_id  Number collaborations     artist_name  \
3044  mn0000545074   mn0000927555                     10  George Michael

     feat_artist_name
3044  Aretha Franklin

         artist_id feat_artist_id  Number collaborations artist_name  \
2591  mn0000379125   mn0000939567                     12  Neil Young

         feat_artist_name
2591  Buffalo Springfield
         artist_id feat_artist_id  Number collaborations artist_name  \
2740  mn0000424078   mn0000942595                     36      Miliki

     feat_artist_name
2740     Café Quijano
         artist_id feat_artist_id  Number collaborations artist_name  \
2444  mn0000354733   mn0000942680                     12   Los Lobos

     feat_artist_name
2444      Café Tacuba
         artist_id feat_artist_id  Number collaborations  artist_name  \
2634  mn0000391586   mn0000944700                      3  James Blunt

     feat_artist_name
2634      Leona Lewis
         artist_id feat_artist_id  Number collaborations  artist_name  \
5153  mn0002996996   mn0000945951                      1  John Newman

     feat_artist_name
5153    Calvin Harris
         artist_id feat_artist_id  Number collaborations artist_name  \
5199  mn0003426731   mn0000945951                      1    Dua Lipa

     feat_artist_name
5199    Calvin Harris
         artist_id feat_artist_id  Number collaborations artist_name  \
4012  mn0000775966   mn0000950726                      9      Chenoa

     feat_artist_name
4012     Gloria Trevi
         artist_id feat_artist_id  Number collaborations      artist_name  \
3848  mn0000756180   mn0000988471                     13  Sinéad O'Connor

     feat_artist_name
3848             Enya
         artist_id feat_artist_id  Number collaborations  artist_name  \
4890  mn0000996127   mn0000996096                      7  Demi Lovato

     feat_artist_name
4890     Selena Gomez
         artist_id feat_artist_id  Number collaborations     artist_name  \
3064  mn0000548397   mn0000996127                     12  Jonas Brothers

     feat_artist_name
3064      Demi Lovato
         artist_id feat_artist_id  Number collaborations   artist_name  \
4881  mn0000996096   mn0000996127                      4  Selena Gomez

     feat_artist_name
4881      Demi Lovato
         artist_id feat_artist_id  Number collaborations artist_name  \
4936  mn0001035294   mn0001013175                     42       Drake

     feat_artist_name
4936      Nicki Minaj
         artist_id feat_artist_id  Number collaborations artist_name  \
2193  mn0000312004   mn0001022592                     11  Luis Fonsi

     feat_artist_name
2193          Pitingo
         artist_id feat_artist_id  Number collaborations artist_name  \
5076  mn0002321707   mn0001022592                      1  Sara Baras

     feat_artist_name
5076          Pitingo
         artist_id feat_artist_id  Number collaborations  artist_name  \
1930  mn0000266063   mn0001035294                     10  Chris Brown

     feat_artist_name
1930            Drake
         artist_id feat_artist_id  Number collaborations  artist_name  \
4905  mn0001013175   mn0001035294                     23  Nicki Minaj

     feat_artist_name
4905            Drake
         artist_id feat_artist_id  Number collaborations   artist_name  \
4947  mn0001287600   mn0000093841                      6  Chris Martin

     feat_artist_name
4947     Chris Martin
        artist_id feat_artist_id  Number collaborations     artist_name  \
880  mn0000127967   mn0001411209                     12  Antonio Orozco

    feat_artist_name
880          Natalia
         artist_id feat_artist_id  Number collaborations  artist_name  \
2301  mn0000329329   mn0001502664                     15  Dani Martín

     feat_artist_name
2301            Leiva
         artist_id feat_artist_id  Number collaborations         artist_name  \
4509  mn0000859026   mn0001502664                     10  Natalia Lafourcade

     feat_artist_name
4509            Leiva
         artist_id feat_artist_id  Number collaborations artist_name  \
4981  mn0001520005   mn0003379732                      2        Nach

     feat_artist_name
4981             Nach
         artist_id feat_artist_id  Number collaborations artist_name  \
4984  mn0001520040   mn0001773187                      2        Taxi

     feat_artist_name
4984             Taxi
         artist_id feat_artist_id  Number collaborations artist_name  \
4447  mn0000846787   mn0001890380                      5      Pereza

     feat_artist_name
4447      Coque Malla
         artist_id feat_artist_id  Number collaborations       artist_name  \
3410  mn0000622555   mn0001976997                      2  Seguridad Social

     feat_artist_name
3410     Sole Giménez
         artist_id feat_artist_id  Number collaborations artist_name  \
2993  mn0000525277   mn0002009120                     17   Ariel Rot

     feat_artist_name
2993   The Cabriolets
         artist_id feat_artist_id  Number collaborations artist_name  \
5037  mn0002011507   mn0000897662                      2     Tequila

     feat_artist_name
5037          Tequila
        artist_id feat_artist_id  Number collaborations artist_name  \
804  mn0000115478   mn0002053263                      3   Cómplices

    feat_artist_name
804         Pignoise
         artist_id feat_artist_id  Number collaborations artist_name  \
5075  mn0002309217   mn0001799394                     58        Vega

     feat_artist_name
5075             Vega
         artist_id feat_artist_id  Number collaborations artist_name  \
4921  mn0001022592   mn0002321707                     16     Pitingo

     feat_artist_name
4921       Sara Baras
         artist_id feat_artist_id  Number collaborations    artist_name  \
2940  mn0000515395   mn0002562509                      4  Pastora Soler

      feat_artist_name
2940  David Bustamante
         artist_id feat_artist_id  Number collaborations   artist_name  \
3468  mn0000635848   mn0002641990                      7  David Bisbal

     feat_artist_name
3468    Pablo Alborán
         artist_id feat_artist_id  Number collaborations artist_name  \
5143  mn0002835269   mn0003185962                     14       Buika

     feat_artist_name
5143            Buika
         artist_id feat_artist_id  Number collaborations    artist_name  \
4814  mn0000945951   mn0002996996                      7  Calvin Harris

     feat_artist_name
4814      John Newman
         artist_id feat_artist_id  Number collaborations artist_name  \
5201  mn0003426731   mn0003011915                      4    Dua Lipa

     feat_artist_name
5201    Martin Garrix
         artist_id feat_artist_id  Number collaborations     artist_name  \
5192  mn0003392996   mn0003276902                      4  Camila Cabello

     feat_artist_name
5192     Shawn Mendes
         artist_id feat_artist_id  Number collaborations artist_name  \
5184  mn0003302932   mn0001602380                      4        Beth

     feat_artist_name
5184             Beth
         artist_id feat_artist_id  Number collaborations   artist_name  \
5182  mn0003276902   mn0003392996                      6  Shawn Mendes

     feat_artist_name
5182   Camila Cabello
         artist_id feat_artist_id  Number collaborations    artist_name  \
4816  mn0000945951   mn0003426731                      4  Calvin Harris

     feat_artist_name
4816         Dua Lipa
         artist_id feat_artist_id  Number collaborations    artist_name  \
5178  mn0003011915   mn0003426731                      5  Martin Garrix

     feat_artist_name
5178         Dua Lipa